"""add_text_value_to_component_properties

Revision ID: 8d87d6306b62
Revises: i7h8a9b0c1d2
Create Date: 2026-01-04 22:20:10.879990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d87d6306b62'
down_revision: Union[str, None] = 'i7h8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_tables_code'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_id'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_name'), table_name='data_tables')
    op.drop_table('data_tables')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_formula_templates_id'), table_name='formula_templates')
    op.drop_table('formula_templates')
    op.drop_index(op.f('ix_property_tables_id'), table_name='property_tables')
    op.drop_table('property_tables')
    op.drop_index(op.f('ix_calculation_templates_id'), table_name='calculation_templates')
    op.drop_table('calculation_templates')
    op.drop_index(op.f('ix_property_formulas_id'), table_name='property_formulas')
    op.drop_table('property_formulas')
    op.drop_index(op.f('ix_formula_validation_rules_id'), table_name='formula_validation_rules')
    op.drop_table('formula_validation_rules')
    op.drop_index(op.f('ix_google_tokens_id'), table_name='google_tokens')
    op.drop_index(op.f('ix_google_tokens_user_email'), table_name='google_tokens')
    op.drop_table('google_tokens')
    op.drop_index(op.f('ix_calculation_history_id'), table_name='calculation_history')
    op.drop_table('calculation_history')
    op.drop_index(op.f('ix_property_table_templates_id'), table_name='property_table_templates')
    op.drop_table('property_table_templates')
    op.drop_index(op.f('ix_property_references_id'), table_name='property_references')
    op.drop_table('property_references')
    op.add_column('component_properties', sa.Column('text_value', sa.String(), nullable=True))
    op.drop_column('component_properties', 'last_calculated')
    op.drop_column('component_properties', 'calculation_status')
    op.drop_column('component_properties', 'is_calculated')
    op.drop_column('component_properties', 'formula_id')
    op.drop_column('component_properties', 'calculation_inputs')
    op.drop_constraint(op.f('components_code_key'), 'components', type_='unique')
    op.drop_index(op.f('ix_components_code'), table_name='components')
    op.create_index(op.f('ix_components_code'), 'components', ['code'], unique=True)
    op.drop_constraint(op.f('materials_code_key'), 'materials', type_='unique')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=True)
    op.drop_index(op.f('ix_model_instances_analyses'), table_name='model_instances', postgresql_where='((component_id IS NULL) AND (name IS NOT NULL))')
    op.drop_index(op.f('uq_model_instances_name_analyses'), table_name='model_instances', postgresql_where='((component_id IS NULL) AND (name IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_model_instances_name_analyses'), 'model_instances', ['name'], unique=True, postgresql_where='((component_id IS NULL) AND (name IS NOT NULL))')
    op.create_index(op.f('ix_model_instances_analyses'), 'model_instances', ['name'], unique=False, postgresql_where='((component_id IS NULL) AND (name IS NOT NULL))')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=False)
    op.create_unique_constraint(op.f('materials_code_key'), 'materials', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_components_code'), table_name='components')
    op.create_index(op.f('ix_components_code'), 'components', ['code'], unique=False)
    op.create_unique_constraint(op.f('components_code_key'), 'components', ['code'], postgresql_nulls_not_distinct=False)
    op.add_column('component_properties', sa.Column('calculation_inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('component_properties', sa.Column('formula_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('component_properties', sa.Column('is_calculated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('component_properties', sa.Column('calculation_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('component_properties', sa.Column('last_calculated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('component_properties', 'text_value')
    op.create_table('property_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formula_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variable_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_component_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_property_definition_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_constant_symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('literal_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('function_args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('units_expected', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('default_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('property_references_pkey'))
    )
    op.create_index(op.f('ix_property_references_id'), 'property_references', ['id'], unique=False)
    op.create_table('property_table_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('property_table_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('table_type', postgresql.ENUM('SINGLE_VAR_LOOKUP', 'RANGE_BASED_LOOKUP', 'MULTI_VAR_LOOKUP', 'REFERENCE_ONLY', name='tabletype'), autoincrement=False, nullable=False),
    sa.Column('independent_vars', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('dependent_vars', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('interpolation_type', postgresql.ENUM('LINEAR', 'LOGARITHMIC', 'POLYNOMIAL', 'RANGE_LOOKUP', 'NONE', name='interpolationtype'), autoincrement=False, nullable=True),
    sa.Column('extrapolation_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('require_monotonic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_from_document', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source_document_example', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='property_table_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_property_table_templates_id'), 'property_table_templates', ['id'], unique=False)
    op.create_table('calculation_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formula_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('calculated_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('calculation_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calculation_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dependencies_resolved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('calculation_history_pkey'))
    )
    op.create_index(op.f('ix_calculation_history_id'), 'calculation_history', ['id'], unique=False)
    op.create_table('google_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('google_tokens_pkey'))
    )
    op.create_index(op.f('ix_google_tokens_user_email'), 'google_tokens', ['user_email'], unique=True)
    op.create_index(op.f('ix_google_tokens_id'), 'google_tokens', ['id'], unique=False)
    op.create_table('formula_validation_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formula_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rule_expression', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('formula_validation_rules_pkey'))
    )
    op.create_index(op.f('ix_formula_validation_rules_id'), 'formula_validation_rules', ['id'], unique=False)
    op.create_table('property_formulas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_definition_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('formula_expression', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validation_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calculation_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depends_on_formulas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_formula_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('property_formulas_pkey'))
    )
    op.create_index(op.f('ix_property_formulas_id'), 'property_formulas', ['id'], unique=False)
    op.create_table('calculation_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_type', postgresql.ENUM('PROPERTY_TABLE', 'WORKFLOW', name='templatetype'), autoincrement=False, nullable=False),
    sa.Column('table_structure', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('calculation_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('calculation_templates_pkey'))
    )
    op.create_index(op.f('ix_calculation_templates_id'), 'calculation_templates', ['id'], unique=False)
    op.create_table('property_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data_points_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('import_method', postgresql.ENUM('DOCUMENT_IMPORT', 'API_IMPORT', 'MANUAL_ENTRY', 'COPIED', name='importmethod'), autoincrement=False, nullable=False),
    sa.Column('source_document_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_document_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_citation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_type', postgresql.ENUM('STANDARD', 'PAPER', 'HANDBOOK', 'REPORT', 'EXPERIMENTAL', 'OTHER', name='sourcetype'), autoincrement=False, nullable=True),
    sa.Column('source_authority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verification_status', postgresql.ENUM('VERIFIED', 'CITED', 'UNVERIFIED', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('verification_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_verified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extracted_via_ocr', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('manual_corrections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_quality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('applicable_conditions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('property_tables_component_id_fkey')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('property_tables_material_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['property_table_templates.id'], name=op.f('property_tables_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('property_tables_pkey'))
    )
    op.create_index(op.f('ix_property_tables_id'), 'property_tables', ['id'], unique=False)
    op.create_table('formula_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_expression', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variable_definitions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('example_usage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('documentation_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference_paper', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('formula_templates_pkey'))
    )
    op.create_index(op.f('ix_formula_templates_id'), 'formula_templates', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('expertise', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('secondary_email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('contacts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey'))
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('data_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('columns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('interpolation', postgresql.ENUM('LINEAR', 'LOGARITHMIC', 'POLYNOMIAL', 'RANGE_LOOKUP', 'NONE', name='interpolationtype'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_tables_pkey'))
    )
    op.create_index(op.f('ix_data_tables_name'), 'data_tables', ['name'], unique=False)
    op.create_index(op.f('ix_data_tables_id'), 'data_tables', ['id'], unique=False)
    op.create_index(op.f('ix_data_tables_code'), 'data_tables', ['code'], unique=True)
    # ### end Alembic commands ###