"""Add property models

Revision ID: 94a2212c4c76
Revises: 
Create Date: 2025-11-07 06:13:12.379640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a2212c4c76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('property_type', sa.Enum('THERMAL', 'ELECTRICAL', 'MECHANICAL', 'ACOUSTIC', 'MATERIAL', 'DIMENSIONAL', 'OPTICAL', 'OTHER', name='propertytype'), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('value_type', sa.Enum('SINGLE', 'RANGE', 'AVERAGE', name='valuetype'), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_unit', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('conversions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('property_definition_id', sa.Integer(), nullable=False),
    sa.Column('single_value', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('average_value', sa.Float(), nullable=True),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('components', 'phase',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PHASE_1', 'PHASE_2', 'PHASE_3', name='rdphase'),
               nullable=False,
               existing_server_default=sa.text("'CYCLE_1'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components', 'phase',
               existing_type=sa.Enum('PHASE_1', 'PHASE_2', 'PHASE_3', name='rdphase'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'CYCLE_1'::character varying"))
    op.drop_table('component_properties')
    op.drop_table('unit_systems')
    op.drop_table('property_definitions')
    # ### end Alembic commands ###